# Use a base image with Java 20
FROM openjdk:20

# Copy the JAR file to the container
COPY /dandelion-lms-backend/lmsbackend/target/*.jar app.jar

EXPOSE 8080
EXPOSE 3306

# Set the entrypoint to run the SpringBoot application
ENTRYPOINT ["java", "-jar", "/app.jar"]